services:
  worker:
    image: node:18-alpine
    mounts:
      - path: /app
        source:
          type: host
          path: ../../mysterybox-backend
    workdir: /app
    env:
      TEMPORAL_GRPC_ENDPOINT: temporal:7233
    cmd:
      - sh
      - -c
      - "npm install && npm run build && node dist/worker.js"
    depends-on:
      - temporal
    labels:
      description: "Temporal worker for processing workflow tasks"
